[package]
name = "accounts_hash"
version = "0.1.0"
authors = ["Daemitrious <evandotschwartzentruber@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.tokio]
version = "1.5.0"
features = ["macros", "rt-multi-thread"]

#[dependencies.rand]
#version = "0.8.4"

[dependencies.serde]
version = "1.0.126"

[dependencies.serde_json]
version = "1.0.64"